# Copyright Elasticsearch B.V. and contributors
# SPDX-License-Identifier: Apache-2.0

# Custom image to start
# To create a multi-arch image, run:
# docker buildx build --platform linux/amd64,linux/arm64 --tag elasticsearch-core-mcp-server .

FROM rust:1.88 AS builder

WORKDIR /app

COPY Cargo.toml Cargo.lock ./

# Cache dependencies
RUN --mount=type=cache,target=/usr/local/cargo/registry \
    --mount=type=cache,target=/app/target \
    mkdir -p ./src/bin && \
    echo "pub fn main() {}" > ./src/bin/elasticsearch-core-mcp-server.rs && \
    cargo build --release

COPY src ./src/

RUN cargo build --release

#--------------------------------------------------------------------------------------------------

FROM debian:stable-slim

RUN <<EOF
    apt-get clean
    apt-get update
    apt-get install --yes libssl-dev ca-certificates
    apt-get clean
    rm -rf /var/lib/apt/lists/*
EOF

COPY --from=builder /app/target/release/elasticsearch-core-mcp-server /usr/local/bin/elasticsearch-core-mcp-server

ENV HTTP_ADDRESS="0.0.0.0:8000"

EXPOSE 8000/tcp
ENTRYPOINT ["/usr/local/bin/elasticsearch-core-mcp-server"]
CMD ["http"]
